### ISSUE TITLE
One Version

### ISSUE THREAD

**Issue by BAROD** [Arkensor/Arma3Log#1]
i would prefer that you use one Version,  before you start with other stuff,
its easier for you to maintain and for other easier to understand

so you can choose with a simple call, what you need

**Comment by Arkensor** [comment]
Well, when i develop one version it's only 1 more click for me to compile the different version as I build a automatic environment that does that for me. The wiki is only copy and paste the case and change the prefix for the 2 versions. Since I have done the work now I will continue to work on all versions at the same time.

Regrads Arkensor

**Comment by BAROD** [comment]
its only my point of view about it you have to decide what you do
